/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116468-g0e09f6d690-20240730"
#endif /* AVUTIL_FFVERSION_H */
